lib/ctbc_web/router.ex
defmodule CtbcWeb.Router do
  use CtbcWeb, :router

  import CtbcWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {CtbcWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CtbcWeb do
    pipe_through [:browser, :require_authenticated_user]
    live "/events", EventLive.Index, :index

    live "/system_users", SystemUserLive.Index, :index
    live "/events/new", EventLive.Index, :new
    live "/events/:id/edit", EventLive.Index, :edit
    live "/tickets", TicketLive.Index, :index
    live "/tickets/new", TicketLive.Index, :new
    live "/tickets/:id/edit", TicketLive.Index, :edit
    live "/tickets/:id/show/edit", TicketLive.Show, :edit

    live "/promo_codes", PromoCodeLive.Index, :index
    live "/promo_codes/new", PromoCodeLive.Index, :new
    live "/promo_codes/:id/edit", PromoCodeLive.Index, :edit

    live "/promo_codes/:id", PromoCodeLive.Show, :show
    live "/promo_codes/:id/show/edit", PromoCodeLive.Show, :edit
    live "/dashboard", DashboardLive.Index, :index
    live "/payments", PaymentLive.Index, :index

    post "/export", ExportController, :create
  end

  scope "/", CtbcWeb do
    pipe_through :browser

    live "/", PageLive.Index, :index

    live "/events/:id", EventLive.Show, :show
    live "/events/:id/:promo_code_name/:promo_code_number", EventLive.PromoCode, :index

    live "/events/:id/:promo_code_name/:promo_code_number/buyticketpromocode",
         EventLive.PromoCode,
         :buyticketpromocode

    live "/events/:id/buyticket", EventLive.Show, :buyticket

    live "/tickets/:ticketid", TicketLive.Show, :show
  end

  # Other scopes may use custom stacks.
  scope "/api", CtbcWeb do
    pipe_through :api
    resources "/mpesa_transactions", MpesaTransactionController, except: [:new, :edit]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", CtbcWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", CtbcWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", CtbcWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/ctbc_web/live/dashboard_live/index.ex
defmodule CtbcWeb.DashboardLive.Index do
  use CtbcWeb, :dashboard_live_view
  alias Ctbc.Tickets
  alias Ctbc.PromoCodes

  alias Ctbc.Users

  def mount(params, session, socket) do
    gate_tickets =
      Tickets.list_tickets()
      |> Enum.filter(fn ticket -> ticket.ticket_type == "Gate" end)

    online_tickets =
      Tickets.list_tickets()
      |> Enum.filter(fn ticket -> ticket.ticket_type == "Online" end)

    promo_tickets =
      Tickets.list_tickets()
      |> Enum.filter(fn ticket -> ticket.ticket_added_type == "Promo" end)

    normal_tickets =
      Tickets.list_tickets()
      |> Enum.filter(fn ticket -> ticket.ticket_added_type == "Normal" end)

    early_bird_tickets =
      Tickets.list_tickets()
      |> Enum.filter(fn ticket -> ticket.event_type == "Early Bird" end)

    advanced_tickets =
      Tickets.list_tickets()
      |> Enum.filter(fn ticket -> ticket.event_type == "Advanced" end)

    flash_sale_tickets =
      Tickets.list_tickets()
      |> Enum.filter(fn ticket -> ticket.event_type == "Flash Sale" end)

    scanned_tickets =
      Tickets.list_tickets()
      |> Enum.filter(fn ticket -> ticket.status == "Scanned" end)

    not_scanned_tickets =
      Tickets.list_tickets()
      |> Enum.filter(fn ticket -> ticket.status == "Not Scanned" end)

    promo_codes = PromoCodes.list_promo_codes()

    all_tickets = Tickets.list_tickets()

    promoters = PromoCodes.list_promo_codes()

    revenue =
      Tickets.list_tickets()
      |> Enum.map(fn ticket -> ticket.total_cost end)
      |> Enum.sum()

    staff =
      Users.list_users()
      |> Enum.filter(fn user -> user.role == "verified" end)

    current_user = Users.get_user_by_session_token(session["user_token"])

    {:ok,
     socket
     |> assign(:url, "/dashboard")
     |> assign(:gate_tickets, gate_tickets)
     |> assign(:revenue, Tickets.format_number(revenue))
     |> assign(:promoters, promoters)
     |> assign(:current_user, current_user)
     |> assign(:online_tickets, online_tickets)
     |> assign(:all_tickets, all_tickets)
     |> assign(:staff, staff)
     |> assign(:promo_codes, promo_codes)
     |> assign(:promo_tickets, promo_tickets)
     |> assign(:normal_tickets, normal_tickets)
     |> assign(:early_bird_tickets, early_bird_tickets)
     |> assign(:advanced_tickets, advanced_tickets)
     |> assign(:flash_sale_tickets, flash_sale_tickets)
     |> assign(:scanned_tickets, scanned_tickets)
     |> assign(:not_scanned_tickets, not_scanned_tickets)}
  end

  def handle_params(params, _url, socket) do
    {:noreply, socket}
  end
end

lib/ctbc_web/live/event_live/buyticket.ex
defmodule CtbcWeb.EventLive.BuyTicketComponent do
  use CtbcWeb, :live_component

  def render(assigns) do
    ~H"""
    <div>
      <div id="myModal" class="modal">
        <div class="modal-content pt-12 ">
          <%= if @payment_state == "initiated" do %>
            <div class="bg-gray-100 rounded-md min-h-[450px] p-2 ">
              <.form let={f} for={@changeset} id="mpesa-form" phx_change="validate" phx_submit="pay">
                <div class="flex flex-col p-2 items-start">
                  <p class="jakrata-regular text-2xl">Pay with Mpesa</p>
                  <div class="flex gap-2 items-center">
                    <p class="bg-black h-[10px] w-[10px] rotate-45" />
                    <p class="bg-red-500 h-[10px] w-[10px] rotate-45" />
                    <p class="bg-green-500 h-[10px] w-[10px] rotate-45" />
                    <p class="bg-yellow-500 h-[10px] w-[10px] rotate-45" />
                    <p class="bg-black h-[10px] w-[10px] rotate-45" />
                    <p class="bg-red-500 h-[10px] w-[10px] rotate-45" />
                    <p class="bg-green-500 h-[10px] w-[10px] rotate-45" />
                    <p class="bg-yellow-500 h-[10px] w-[10px] rotate-45" />
                    <p class="bg-black h-[10px] w-[10px] rotate-45" />
                    <p class="bg-red-500 h-[10px] w-[10px] rotate-45" />
                    <p class="bg-green-500 h-[10px] w-[10px] rotate-45" />
                    <p class="bg-yellow-500 h-[10px] w-[10px] rotate-45" />
                  </div>
                </div>
                <p class="  h-[2px] my-2 bg-gradient-to-r from-green-300  via-green-700 to-black   w-[100%]" />
                <div class="flex  px-2 gap-2 items-center">
                  <p class="bg-gradient-to-tl  from-green-500  via-green-700 to-black px-8 to-black py-2 text-xl  rounded-md text-white">
                    Ksh <%= @event.price %> per ticket
                  </p>
                </div>
                <div class="w-[100%] flex  md:flex-row flex-col justify-between">
                  <div class="md:w-[48%]">
                    <p>
                      Enter your Name
                    </p>

                    <div>
                      <%= text_input(f, :name,
                        placeholder: "Full Name",
                        class:
                          "w-[100%] rounded-md  h-[40px] focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                      ) %>
                    </div>
                    <p class="pt-5">
                      <%= error_tag(f, :name) %>
                    </p>
                  </div>
                  <div class="md:w-[48%] ">
                    <p>
                      Enter your Email
                    </p>

                    <div>
                      <%= text_input(f, :email,
                        placeholder: "customer@gmail.com",
                        class:
                          "w-[100%] rounded-md  h-[40px] focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                      ) %>
                    </div>
                    <p class="pt-5">
                      <%= error_tag(f, :email) %>
                    </p>
                  </div>
                </div>
                <div>
                  <p>
                    Enter your Mpesa Number to get a prompt
                  </p>

                  <p class="text-red-500 text-sm">
                    *Ensure the phone number starts with 254 , e.g 254712345678
                  </p>
                  <div>
                    <%= text_input(f, :phone_number,
                      placeholder: "254712345678",
                      class:
                        "w-[100%] rounded-md  h-[40px] focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                    ) %>
                  </div>
                  <p class="pt-5">
                    <%= error_tag(f, :phone_number) %>
                  </p>
                </div>
                <div class="my-2">
                  <p>
                    Enter Number of Tickets
                  </p>
                  <%= select(f, :no_of_tickets, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    prompt: "Select the number of tickets",
                    class:
                      "w-[100%] rounded-md focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                  ) %>
                  <p class="pt-5">
                    <%= error_tag(f, :no_of_tickets) %>
                  </p>
                </div>

                <div>
                  <p>
                    Select how you want to receive your ticket
                  </p>
                  <div>
                    <%= select(f, :deliver_ticket_by, ["SMS", "Email Address"],
                      prompt: "Select ",
                      class:
                        "w-[100%] rounded-md  h-[40px] focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                    ) %>
                  </div>
                  <p class="pt-5">
                    <%= error_tag(f, :deliver_ticket_by) %>
                  </p>
                </div>

                <%= if @number_of_tickets != "" do %>
                  <p class="p-2 jakrata-regular text-xl text-center">
                    The total cost for <%= @number_of_tickets %> <%= if String.to_integer(
                                                                          @number_of_tickets
                                                                        ) == 1 do
                      "ticket"
                    else
                      "tickets"
                    end %> is Ksh <%= @total_cost %>
                  </p>
                <% end %>

                <div class="flex flex-col w-[100%] p-2 items-start">
                  <%= submit("Buy Ticket",
                    phx_disable_with: "Submitting Payment",
                    class:
                      "bg-gradient-to-l w-[80%] mx-auto rounded-md  text-white  uppercase font-semibold py-2 hover:scale-105 transition-all ease-in-out transition-all duration-500 cursor-pointer from-green-200  via-green-500 to-black"
                  ) %>
                </div>
              </.form>
            </div>
          <% else %>
            <div class="bg-gray-100 flex rounded-md flex-col justify-center items-center gap-8 h-[450px] p-2 ">
              <p class="bg-yellow-400 w-[80%] mx-auto p-4 rounded-md text-xl text-center">
                A Prompt has been sent  to your phone to pay Ksh <%= @total_cost %> for <%= @ticket_number %> tickets .
                Kindly complete the payment to get your ticket and once you are done , click the confirm button below.
              </p>
              <div class="flex justify-center items-center">
                <button
                  phx-click="check"
                  phx-disable-with="Confirming Payment.."
                  class="bg-gradient-to-l px-8  mx-auto rounded-md  text-white  uppercase font-semibold py-2 hover:scale-105 transition-all ease-in-out transition-all duration-500 cursor-pointer from-green-400  via-green-500 to-black"
                >
                  Confirm
                </button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    """
  end
end

lib/ctbc_web/live/event_live/form_component.ex
defmodule CtbcWeb.EventLive.FormComponent do
  use CtbcWeb, :live_component

  alias Ctbc.Events

  @impl true
  def update(%{event: event} = assigns, socket) do
    changeset = Events.change_event(event)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"event" => event_params}, socket) do
    changeset =
      socket.assigns.event
      |> Events.change_event(event_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"event" => event_params}, socket) do
    save_event(socket, socket.assigns.action, event_params)
  end

  defp save_event(socket, :edit, event_params) do
    case Events.update_event(socket.assigns.event, event_params) do
      {:ok, _event} ->
        {:noreply,
         socket
         |> put_flash(:info, "Event updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_event(socket, :new, event_params) do
    IO.inspect(event_params)

    case Events.create_event(event_params) do
      {:ok, _event} ->
        {:noreply,
         socket
         |> put_flash(:info, "Event created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/ctbc_web/live/event_live/index.ex
defmodule CtbcWeb.EventLive.Index do
  use CtbcWeb, :dashboard_live_view

  alias Ctbc.Events
  alias Ctbc.Events.Event
  alias Ctbc.Users

  @impl true
  def mount(_params, session, socket) do
    current_user = Users.get_user_by_session_token(session["user_token"])

    {:ok,
     socket
     |> assign(:events, list_events())
     |> assign(:url, "/events")
     |> assign(:current_user, current_user)}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Event")
    |> assign(:event, Events.get_event!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Event")
    |> assign(:event, %Event{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Events")
    |> assign(:event, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    event = Events.get_event!(id)
    {:ok, _} = Events.delete_event(event)

    {:noreply, assign(socket, :events, list_events())}
  end

  defp list_events do
    Events.list_events()
  end
end

lib/ctbc_web/live/mpesa_live/show.ex
defmodule CtbcWeb.MpesaLive.Show do
  use CtbcWeb, :live_view

  alias Ctbc.Mpesas

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:mpesa, Mpesas.get_mpesa!(id))}
  end

  defp page_title(:show), do: "Show Mpesa"
  defp page_title(:edit), do: "Edit Mpesa"
end

lib/ctbc_web/live/ticket_live/index.html.heex
<%= if @live_action in [:new, :edit] do %>
  <.modal return_to={Routes.ticket_index_path(@socket, :index)}>
    <.live_component
      module={CtbcWeb.TicketLive.FormComponent}
      id={@ticket.id || :new}
      title={@page_title}
      action={@live_action}
      ticket={@ticket}
      current_user={@current_user}
      events={@events}
      return_to={Routes.ticket_index_path(@socket, :index)}
    />
  </.modal>
<% end %>

<div class="flex flex-col w-[100%] gap-2">
  <div class="flex flex-col gap-1">
    <div class="flex flex-row items-center justify-between w-[100%]">
      <p>
        You have a total of <%= @count %> tickets
      </p>
      <div class="flex gap-2 items-center">
        <div class="flex justify-end ">
          <%= link to: Routes.export_path(@socket, :create), class: "btn btn-secondary", method: :post do %>
            <button class="bg-green-500 flex gap-2 items-center text-white  rounded-md p-2">
              <%= Heroicons.icon("arrow-down-tray",
                type: "solid",
                class: "h-8   font-bold w-8"
              ) %> Export
            </button>
          <% end %>
        </div>
        <%= live_patch(to: Routes.ticket_index_path(@socket, :new)) do %>
          <button class="bg-green-500 flex gap-2 items-center text-white  rounded-md p-2">
            <%= Heroicons.icon("plus",
              type: "solid",
              class: "h-8   font-bold w-8"
            ) %> New Ticket
          </button>
        <% end %>
      </div>
    </div>
  </div>
  <div class="flex justify-between">
    <div class="w-[30%] flex flex-col gap-1">
      <p>
        Search by any
      </p>
      <.form let={f} for={@changeset} class="w-[100%]" phx_change="search">
        <%= text_input(f, :search,
          placeholder: "Search ticket number or phone",
          class:
            "w-[100%] rounded-md border-transparent focus:border-transparent focus:ring-0  border-gray-300 border-2 p-2"
        ) %>
      </.form>
    </div>

    <div class="w-[22%] flex flex-col gap-1">
      <p>
        Filter Scanned
      </p>

      <.form let={f} for={@changeset} class="w-[100%]" phx_change="filter_by_status">
        <%= select(f, :status, ["Scanned", "Not Scanned"],
          prompt: "Filter Scans",
          class:
            "w-[100%] rounded-md border-transparent focus:border-transparent focus:ring-0  border-gray-300 border-2 p-2 "
        ) %>
      </.form>
    </div>
    <div class="w-[22%] flex flex-col gap-1">
      <p>
        Filter Promo Tickets
      </p>

      <.form let={f} for={@changeset} phx_change="filter_by_promo">
        <%= select(f, :promo, ["Normal", "Promo"],
          prompt: "Filter Promo Tickets",
          class:
            "  w-[100%] rounded-md border-transparent focus:border-transparent focus:ring-0  border-gray-300 border-2 p-2"
        ) %>
      </.form>
    </div>

    <div class="w-[22%] flex flex-col gap-1">
      <p>
        Filter Gate Type
      </p>

      <.form let={f} for={@changeset} phx_change="filter_by_type">
        <%= select(f, :type, ["Gate", "Online"],
          prompt: "Filter Gate Tickets",
          class:
            " w-[100%] rounded-md border-transparent focus:border-transparent focus:ring-0  border-gray-300 border-2 p-2 "
        ) %>
      </.form>
    </div>
  </div>

  <div class="bg-white h-[60vh] flex justify-between flex-col  rounded-xl p-4 overflow-y-scroll">
    <table class="w-[100%]">
      <thead class="border-b-2  border-black">
        <tr>
          <th class="p-2 font-semibold text-gray-700">Ticketid</th>
          <th class="p-2 font-semibold text-gray-700">Quantity</th>
          <th class="p-2 font-semibold text-gray-700">Ticket</th>

          <th class="p-2 font-semibold text-gray-700">Event</th>
          <th class="p-2 font-semibold text-gray-700">Status</th>
          <th class="p-2 font-semibold text-gray-700">Number</th>
          <th class="p-2 font-semibold text-gray-700">Name</th>
          <th class="p-2 font-semibold text-gray-700">Email</th>
          <th class="p-2 font-semibold text-gray-700">PromoName</th>
          <th class="p-2 font-semibold text-gray-700">PromoNo</th>
          <th class="p-2 font-semibold text-gray-700">Send SMS</th>
          <th class="p-2 font-semibold text-gray-700">Send Email</th>

          <th class="p-2 font-semibold text-gray-700">Actions</th>
        </tr>
      </thead>
      <tbody id="tickets">
        <%= for ticket <- @tickets do %>
          <tr
            id={"ticket-#{ticket.id}"}
            class="border-b-[1px] cursor-pointer text-center hover:bg-blue-100/50 transition-all ease-in-out duration-500  border-black"
          >
            <td class="p-1"><%= ticket.ticketid %></td>
            <td class="p-1"><%= ticket.quantity %></td>
            <td class="p-1"><%= ticket.ticket_type %></td>
            <td class="w-[100%] p-2 ">
              <div class="flex flex-col ">
                <p class="w-[150px]">
                  <%= ticket.event_type %>
                </p>
              </div>
            </td>
            <td class="w-[100%]">
              <div class="flex flex-col ">
                <%= if ticket.status == "Scanned" do %>
                  <span class="bg-green-500    text-white rounded-md p-1">
                    <%= ticket.status %>
                  </span>
                <% else %>
                  <span class="bg-red-500 w-[150px]  break-keep  text-white rounded-md p-1">
                    <%= ticket.status %>
                  </span>
                <% end %>
              </div>
            </td>
            <td class="p-1"><%= ticket.phone_number %></td>
            <td class="p-1"><%= ticket.ticket_holder_name %></td>
            <td class="p-1"><%= ticket.ticket_holder_email %></td>
            <td class="p-1"><%= ticket.promo_code_name %></td>
            <td class="p-1"><%= ticket.promo_code_number %></td>
            <td class="p-1">
              <button
                phx-click="send_sms"
                phx-value-id={ticket.id}
                class=" bg-green-500 flex gap-2 w-[200px] justify-center items-center text-white  rounded-md p-2 "
              >
                Send SMS
              </button>
            </td>
            <td class="p-1">
              <button
                phx-click="send_email"
                phx-value-id={ticket.id}
                class=" bg-green-500 flex gap-2 w-[200px] justify-center items-center text-white  rounded-md p-2 "
              >
                Send Email
              </button>
            </td>

            <td>
              <div class="flex flex-row gap-2 justify-center items-center">
                <div>
                  <%= live_redirect(to: Routes.ticket_show_path(@socket, :show, ticket.ticketid)) do %>
                    <%= Heroicons.icon("eye",
                      type: "solid",
                      class: "h-6  group-hover:text-green-600 text-green-400 w-6"
                    ) %>
                  <% end %>
                </div>

                <div>
                  <%= live_patch(to: Routes.ticket_index_path(@socket, :edit, ticket)) do %>
                    <%= Heroicons.icon("pencil",
                      type: "solid",
                      class: "h-6  group-hover:text-blue-600 text-blue-400 w-6"
                    ) %>
                  <% end %>
                </div>

                <div>
                  <%= link(
                    to: "#",
                    phx_click: "delete",
                    phx_value_id: ticket.id,
                    data: [confirm: "Are you sure?"]
                  )  do %>
                    <%= Heroicons.icon("trash",
                      type: "solid",
                      class: "h-6  group-hover:text-red-600 text-red-400 w-6"
                    ) %>
                  <% end %>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="flex flex-wrap flex-row p-2">
      <%= if @page_number > 1 do %>
        <%= live_patch(
            to: Routes.ticket_index_path(@socket, :index, page: @page_number - 1),
            class: "pagination-link"
          ) do %>
          <div class="flex gap-2 items-center ">
            Previous
          </div>
        <% end %>
      <% end %>

      <%= for idx <-  Enum.to_list(1..@total_pages) do %>
        <%= live_patch(
            to: Routes.ticket_index_path(@socket, :index, page: idx),
            class: "pagination-link"
          ) do %>
          <%= if @page_number == idx do %>
            <p class="bg-green-500    text-white px-2 border-white border-transparent ">
              <%= idx %>
            </p>
          <% else %>
            <p class="px-2   border-white">
              <%= idx %>
            </p>
          <% end %>
        <% end %>
      <% end %>

      <%= if @page_number < @total_pages do %>
        <%= live_patch(
            to: Routes.ticket_index_path(@socket, :index, page: @page_number + 1),
            class: "pagination-link"
          )  do %>
          <div class="flex gap-2 items-center ">
            Next
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>