lib/ctbc_web/router.ex
defmodule CtbcWeb.Router do
  use CtbcWeb, :router

  import CtbcWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {CtbcWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CtbcWeb do
    pipe_through [:browser, :require_authenticated_user]
    live "/events", EventLive.Index, :index

    live "/system_users", SystemUserLive.Index, :index
    live "/events/new", EventLive.Index, :new
    live "/events/:id/edit", EventLive.Index, :edit
    live "/tickets", TicketLive.Index, :index
    live "/tickets/new", TicketLive.Index, :new
    live "/tickets/:id/edit", TicketLive.Index, :edit
    live "/tickets/:id/show/edit", TicketLive.Show, :edit

    live "/promo_codes", PromoCodeLive.Index, :index
    live "/promo_codes/new", PromoCodeLive.Index, :new
    live "/promo_codes/:id/edit", PromoCodeLive.Index, :edit

    live "/promo_codes/:id", PromoCodeLive.Show, :show
    live "/promo_codes/:id/show/edit", PromoCodeLive.Show, :edit
    live "/dashboard", DashboardLive.Index, :index
    live "/payments", PaymentLive.Index, :index

    post "/export", ExportController, :create
  end

  scope "/", CtbcWeb do
    pipe_through :browser

    live "/", PageLive.Index, :index

    live "/events/:id", EventLive.Show, :show
    live "/events/:id/:promo_code_name/:promo_code_number", EventLive.PromoCode, :index

    live "/events/:id/:promo_code_name/:promo_code_number/buyticketpromocode",
         EventLive.PromoCode,
         :buyticketpromocode

    live "/events/:id/buyticket", EventLive.Show, :buyticket

    live "/tickets/:ticketid", TicketLive.Show, :show
  end

  # Other scopes may use custom stacks.
  scope "/api", CtbcWeb do
    pipe_through :api
    resources "/mpesa_transactions", MpesaTransactionController, except: [:new, :edit]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", CtbcWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", CtbcWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", CtbcWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/ctbc_web/views/layout_view.ex
defmodule CtbcWeb.LayoutView do
  use CtbcWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/ctbc_web/templates/layout/_user_menu.html.heex
<ul>
  <%= if @current_user do %>
    <li><%= @current_user.email %></li>
    <li><%= link("Settings", to: Routes.user_settings_path(@conn, :edit)) %></li>
    <li><%= link("Log out", to: Routes.user_session_path(@conn, :delete), method: :delete) %></li>
  <% else %>
    <li><%= link("Register", to: Routes.user_registration_path(@conn, :new)) %></li>
    <li><%= link("Log in", to: Routes.user_session_path(@conn, :new)) %></li>
  <% end %>
</ul>

lib/ctbc_web/templates/layout/app.html.heex
<main>
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/ctbc_web/templates/layout/dashboard_live.html.heex
<main>
  <%= if @flash["info"] do %>
    <p
      class="alert alert-info hideMsg"
      role="alert"
      phx-click="lv:clear-flash"
      phx-value-key="info"
    >
      <%= live_flash(@flash, :info) %>
    </p>
  <% end %>

  <%= if @flash["error"] do %>
    <p
      class="alert alert-danger hideMsg"
      role="alert"
      phx-click="lv:clear-flash"
      phx-value-key="error"
    >
      <%= live_flash(@flash, :error) %>
    </p>
  <% end %>
  <div class="bg-[#F5F6FA] w-[100%] flex  ">
    <div class="w-[20%] m-4 rounded-md fixed h-[90vh] jakrata-regular hidden gap-4  md:flex text-xl flex-col justify-start p-4 bg-white  bg-cover">
      <%= live_redirect to: Routes.page_index_path(@socket, :index) , class: " w-[100px] flex justify-start items-start" do %>
        <img src="/images/logo.png" class="w-[80px] h-[80px] object-contain" />
      <% end %>

      <%= if @url == "/dashboard" do %>
        <%= live_redirect to: Routes.dashboard_index_path(@socket, :index) do %>
          <div class="flex gap-2  bg-green-500 text-white rounded-md   p-2 items-center">
            <%= Heroicons.icon("table-cells",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              Dashboard
            </p>
          </div>
        <% end %>
      <% else %>
        <%= live_redirect to: Routes.dashboard_index_path(@socket, :index)  do %>
          <div class="flex gap-2   p-2 items-center">
            <%= Heroicons.icon("table-cells",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              Dashboard
            </p>
          </div>
        <% end %>
      <% end %>

      <%= if @url == "/events" do %>
        <%= live_redirect to: Routes.event_index_path(@socket, :index)  do %>
          <div class="flex gap-2  bg-green-500 text-white rounded-md   p-2 items-center">
            <%= Heroicons.icon("calendar",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              Events
            </p>
          </div>
        <% end %>
      <% else %>
        <%= live_redirect to: Routes.event_index_path(@socket, :index)  do %>
          <div class="flex gap-2   p-2 items-center">
            <%= Heroicons.icon("calendar",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              Events
            </p>
          </div>
        <% end %>
      <% end %>

      <%= if @url == "/tickets" do %>
        <%= live_redirect to: Routes.ticket_index_path(@socket, :index)  do %>
          <div class="flex gap-2  bg-green-500 text-white rounded-md   p-2 items-center">
            <%= Heroicons.icon("ticket",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              Tickets
            </p>
          </div>
        <% end %>
      <% else %>
        <%= live_redirect to: Routes.ticket_index_path(@socket, :index)  do %>
          <div class="flex gap-2   p-2 items-center">
            <%= Heroicons.icon("ticket",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              Tickets
            </p>
          </div>
        <% end %>
      <% end %>

      <%= if @url == "/promo_codes" do %>
        <%= live_redirect to: Routes.promo_code_index_path(@socket, :index)  do %>
          <div class="flex gap-2  bg-green-500 text-white rounded-md   p-2 items-center">
            <%= Heroicons.icon("qr-code",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              Promo Codes
            </p>
          </div>
        <% end %>
      <% else %>
        <%= live_redirect to: Routes.promo_code_index_path(@socket, :index)  do %>
          <div class="flex gap-2   p-2 items-center">
            <%= Heroicons.icon("qr-code",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              Promo Codes
            </p>
          </div>
        <% end %>
      <% end %>

      <%= if @url == "/payments" do %>
        <%= live_redirect to: Routes.payment_index_path(@socket, :index)  do %>
          <div class="flex gap-2  bg-green-500 text-white rounded-md   p-2 items-center">
            <%= Heroicons.icon("banknotes",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              Payments
            </p>
          </div>
        <% end %>
      <% else %>
        <%= live_redirect to: Routes.payment_index_path(@socket, :index)  do %>
          <div class="flex gap-2   p-2 items-center">
            <%= Heroicons.icon("banknotes",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              Payments
            </p>
          </div>
        <% end %>
      <% end %>

      <%= if @url == "/system_users" do %>
        <%= live_redirect to: Routes.system_user_index_path(@socket, :index)  do %>
          <div class="flex gap-2  bg-green-500 text-white rounded-md   p-2 items-center">
            <%= Heroicons.icon("user-group",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              System Users
            </p>
          </div>
        <% end %>
      <% else %>
        <%= live_redirect to: Routes.system_user_index_path(@socket, :index)  do %>
          <div class="flex gap-2   p-2 items-center">
            <%= Heroicons.icon("user-group",
              type: "solid",
              class: "h-6   font-bold w-6"
            ) %>
            <p>
              System Users
            </p>
          </div>
        <% end %>
      <% end %>

      <%= link(to: Routes.user_settings_path(@socket, :edit))  do %>
        <div class="flex gap-2   p-2 items-center">
          <%= Heroicons.icon("cog-6-tooth",
            type: "solid",
            class: "h-8   font-bold w-6"
          ) %>
          <p>
            Settings
          </p>
        </div>
      <% end %>
      <%= link to: Routes.user_session_path(@socket, :delete), method: :delete  do %>
        <div class="flex gap-2   p-2 items-center">
          <%= Heroicons.icon("power",
            type: "solid",
            class: "h-6   font-bold w-6"
          ) %>
          <p>
            Logout
          </p>
        </div>
      <% end %>
    </div>

    <div class="flex w-[100%] overflow-scroll m-4  min-h-[100vh] ml-[25%] flex-col gap-4">
      <div class="flex w-[100%] justify-between">
        <p>
          The Kulture Ke
        </p>

        <div class="flex gap-2 items-center">
          <p class="bg-black h-[10px] w-[10px] rotate-45" />
          <p class="bg-red-500 h-[10px] w-[10px] rotate-45" />
          <p class="bg-green-500 h-[10px] w-[10px] rotate-45" />
          <p class="bg-yellow-500 h-[10px] w-[10px] rotate-45" />
          <p class="bg-black h-[10px] w-[10px] rotate-45" />
          <p class="bg-red-500 h-[10px] w-[10px] rotate-45" />
          <p class="bg-green-500 h-[10px] w-[10px] rotate-45" />
          <p class="bg-yellow-500 h-[10px] w-[10px] rotate-45" />
          <p class="bg-black h-[10px] w-[10px] rotate-45" />
          <p class="bg-red-500 h-[10px] w-[10px] rotate-45" />
          <p class="bg-green-500 h-[10px] w-[10px] rotate-45" />
          <p class="bg-yellow-500 h-[10px] w-[10px] rotate-45" />
        </div>
      </div>

      <div class="w-[100%] flex justify-between ">
        <p class="text-gray-600 font-bold text-3xl ">
          <%= @url |> String.replace("/", "") |> String.replace("_", "") |> String.capitalize() %>
        </p>

        <div class="flex gap-2 items-center">
          <p class="bg-green-500 uppercase w-[50px] flex flex-col justify-center items-center h-[50px]  rounded-full text-2xl text-white font-semibold ">
            <%= @current_user.email |> String.at(0) %>
          </p>
        </div>
      </div>

      <%= @inner_content %>
    </div>
  </div>
</main>

lib/ctbc_web/templates/layout/live.html.heex
<main>
  <%= if @flash["info"] do %>
    <p
      class="alert alert-info hideMsg"
      role="alert"
      phx-click="lv:clear-flash"
      phx-value-key="info"
    >
      <%= live_flash(@flash, :info) %>
    </p>
  <% end %>

  <%= if @flash["error"] do %>
    <p
      class="alert alert-danger hideMsg"
      role="alert"
      phx-click="lv:clear-flash"
      phx-value-key="error"
    >
      <%= live_flash(@flash, :error) %>
    </p>
  <% end %>

  <%= @inner_content %>
</main>

lib/ctbc_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="csrf-token" content={csrf_token_value()} />
    <%= live_title_tag(assigns[:page_title] || "Ctbc", suffix: " · Phoenix Framework") %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")} />
    <script
      defer
      phx-track-static
      type="text/javascript"
      src={Routes.static_path(@conn, "/assets/app.js")}
    >
    </script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css" />
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js">
    </script>

    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css"
    />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js ">
    </script>

    <script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js">
    </script>

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.0/chart.min.js"
      integrity="sha512-7U4rRB8aGAHGVad3u2jiC7GA5/1YhQcQjxKeaVms/bT66i3LVBMRcBI9KwABNWnxOSwulkuSXxZLGuyfvo7V1A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    >
    </script>
    <script
      src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.js"
    >
    </script>

    <script type="text/JavaScript" src=" https://MomentJS.com/downloads/moment.js">
    </script>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.css" rel="stylesheet" />
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.js">
    </script>
    <link
      rel="stylesheet"
      href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.css"
      type="text/css"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js">
    </script>
    <script src="html5-qrcode.min.js">
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js ">
    </script>
  </head>
  <body>
    <%= @inner_content %>
    <%!-- <%= render("_user_menu.html", assigns) %> --%>
  </body>
</html>